global:
  networkPolicies:
    enabled: true

controller:
  resources:
    requests:
      cpu: 250m
      memory: 512Mi
    limits:
      cpu: 500m
      memory: 1Gi
  # Esto arregla lo de los puertos que Popeye criticaba
  containerPort: 8082
  livenessProbe:
    httpGet:
      path: /healthz
      port: 8082
    initialDelaySeconds: 10
  readinessProbe:
    httpGet:
      path: /healthz
      port: 8082

server:
  ingress:
    enabled: true
    ingressClassName: traefik
    hosts:
      - argocd.local
  extraArgs:
    - --insecure # Clave para que Traefik no se vuelva loco

repoServer:
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 200m
      memory: 512Mi

