global:
  domain: argocd.local
  networkPolicies:
    enabled: true
  # Popeye odia los contenedores que no tienen recursos definidos a nivel global
  logging:
    level: info

# Configuración del Controller
controller:
  resources:
    requests:
      cpu: 250m
      memory: 512Mi
    limits:
      cpu: 500m
      memory: 1Gi
  # Popeye pide SecurityContext para evitar escalada de privilegios
  containerSecurityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop:
        - ALL
    readOnlyRootFilesystem: true
    runAsNonRoot: true

# Configuración del Server
server:
  extraArgs:
    - --insecure
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 200m
      memory: 512Mi
  containerSecurityContext:
    allowPrivilegeEscalation: false
    readOnlyRootFilesystem: fakse
  ingress:
    enabled: true
    ingressClassName: traefik
    hosts:
      - argocd.local
    hostname: argocd.local
    annotations:
      kubernetes.io/ingress.class: traefik
      traefik.ingress.kubernetes.io/service.serversscheme: http
      #traefik.ingress.kubernetes.io/router.entrypoints: websecure
      #traefik.ingress.kubernetes.io/router.tls: "true"
    paths:
      - /
    pathType: Prefix
    https: false

# El Repo Server suele ser un punto ciego que baja puntos
repoServer:
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 200m
      memory: 512Mi
  containerSecurityContext:
    allowPrivilegeEscalation: false
    readOnlyRootFilesystem: true

# ¡IMPORTANTE! Redis suele venir "desnudo" en la instalación default
redis:
  enabled: true
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 256Mi
  containerSecurityContext:
    allowPrivilegeEscalation: false
    readOnlyRootFilesystem: true

# Application Set Controller (si lo usas)
applicationSet:
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 256Mi

